server:
  port: 8083

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: message

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: metawater
    password: 1234


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.metawater
#  type-aliases-package: com.example.metajobs

